# Generated by Django 5.2.4 on 2025-09-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post-author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post-blog',
            new_name='post',
        ),
    ]
